name: Stream Audio to ZenoFM

on:
  schedule:
    - cron: '5 22 * * *'  # 4:05 AM BDT (UTC+6)
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    env:
      ZENO_PASSWORD: ${{ secrets.ZENO_PASSWORD }}
    steps:
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Start Streaming Audio to ZenoFM
        run: |
          ffmpeg -loglevel info -re \
          -i "https://archive.org/download/MuftiAbdurRahmanSahabBayanInMasturath/Mufti%20Abdur%20Rahman%20Sahab%20Bayan%20in%20masturath.mp3" \
          -t 00:20:00 \
          -vn \
          -c:a libmp3lame \
          -b:a 128k \
          -content_type audio/mpeg \
          -legacy_icecast 1 \
          -ice_name "আজকের বয়ান" \
          -ice_description "মুফতি তাকি উসমানি, তাফসির মাহফিল" \
          -ice_genre "Islamic" \
          -f mp3 \
          "icecast://source:${ZENO_PASSWORD}@link.zeno.fm:80/ghcsb5a7ma0uv"
