name: Stream Audio to ZenoFM

on:
  schedule:
    - cron: '10 21 * * *' # UTC time = 3:10 AM BD time
  workflow_dispatch: # allows manual run from GitHub Actions UI

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Start Streaming Audio to ZenoFM
        run: |
          ffmpeg -re \
          -i "https://archive.org/download/MuftiAbdurRahmanSahabBayanInMasturath/Mufti%20Abdur%20Rahman%20Sahab%20Bayan%20in%20masturath.mp3" \
          -t 00:20:00 \
          -vn \
          -c:a libmp3lame \
          -b:a 128k \
          -content_type audio/mpeg \
          -legacy_icecast 1 \
          -ice_name "আজকের বয়ান" \
          -ice_description "মুফতি তাকি উসমানি, তাফসির মাহফিল" \
          -ice_genre "Islamic" \
          -f mp3 \
          "icecast://source:rfdjjQJh@link.zeno.fm:80/ghcsb5a7ma0uv"
