name: Stream to ZenoFM

on:
  schedule:
    - cron: '15 8 * * *'  # প্রতি দিন বাংলাদেশ সময় দুপুর ২:১৫ (UTC 08:15)
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start Streaming Directly
      run: |
        ffmpeg -re -i "https://ia800405.us.archive.org/3/items/MuftiAbdurRahmanSahabBayanInMasturath/Mufti%20Abdur%20Rahman%20Sahab%20Bayan%20in%20masturath.mp3" \
        -vn -c:a libmp3lame -b:a 128k -content_type audio/mpeg -legacy_icecast 1 \
        -f mp3 "icecast://source:rfdjjQJh@link.zeno.fm:80/ghcsb5a7ma0uv"
